### ISSUE TITLE
Reading of Symbolic Names instead of Address

### ISSUE THREAD

**Issue by Terr4** [nicolasme/s7comm#7]
Hello,

Is there any way to read the symbolic names from the Siemens PLCs instead of the Addresses? I can only find the example to read values with addresses.
Reading addresses is considered a legacy method to read values.

thanks

**Comment by nicolasme** [comment]
Hello,

Sorry, it's not possible with the communication type used. You should look for the OPC.UA plugin if you have a recent PLC.

Regards

**Comment by Terr4** [comment]
> Hello,
> 
> Sorry, it's not possible with the communication type used. You should look for the OPC.UA plugin if you have a recent PLC.
> 
> Regards

Thank you for the hint!

Just for my understanding:
Does it mean symbolic addressing is only possible with OPC-UA or just that the communication type the plugin uses right now can only do addresses?

Here is a description of what I mean:
https://www.360digitalgyan.com/what-is-absolute-and-symbolic-addressing-in-s7-300-plc

thanks!
